name: build

on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: pull
        run: |
          git clone https://github.com/jellyfin/jellyfin-packaging.git
          cd jellyfin-packaging
          git submodule update --init
          mv docker/Dockerfile ./
          sed -i '/EXPOSE 8096/a RUN bash /run.sh' Dockerfile
          sed -i '/EXPOSE 8096/a COPY run.sh /run.sh' Dockerfile
          mv ../run.sh ./
          cd ..
      - name: Release and push
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:jellyfin-packaging"
          push: true
          tags: ghcr.io/dream10201/jellyfin:latest,docker.io/xiuxiu10201/jellyfin:latest
